<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MailWinnow.Core\MailWinnow.Core.csproj" />
    <ProjectReference Include="..\MailWinnow.Infrastructure\MailWinnow.Infrastructure.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <VersionPrefix>1.7.0</VersionPrefix>
    <BuildNumber>100</BuildNumber>
    <Version>$(VersionPrefix)</Version>
    <AssemblyVersion>$(VersionPrefix).$(BuildNumber)</AssemblyVersion>
    <FileVersion>$(VersionPrefix).$(BuildNumber)</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <InformationalVersion>$(VersionPrefix).$(BuildNumber)</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MailWinnow.Tests" />
  </ItemGroup>
</Project>